# Generated by Django 4.2.13 on 2024-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='last_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
